services:
  nginx:
    init: true
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app
  myserver1:
    init: true
    build: ./server
    ports:
      - '1111:7777'
  myserver2:
    init: true
    build: ./server
    ports:
      - '2222:7777'
  myserver3:
    init: true
    build: ./server
    ports:
      - '3333:7777'
  myserver4:
    init: true
    build: ./server
    ports:
      - '4444:7777'